source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.7', '>= 6.1.7.7'
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 4.1.0'
  # Display performance information such as SQL time and flame graphs for each request in your browser.
  # Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
  gem 'rack-mini-profiler', '~> 2.0'
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "jinda", path: "../../../jinda"
gem "jinda_adminlte", path: "../../../jinda_adminlte"
gem 'bson', '4.15'
gem 'maruku', '~> 0.7.3'
gem 'bcrypt'
gem 'rouge'
gem 'normalize-rails'
gem 'font-awesome-rails'
gem 'font-awesome-sass', '~> 5.12.0'
gem 'meta-tags'
gem 'jquery-turbolinks', '2.1.0'
gem 'mongo'
gem 'turbolinks_render'
gem 'haml-rails', '~> 2.0.1'
gem 'prawn'
gem 'redcarpet'
gem 'oauth2', '1.4.4'
gem 'omniauth', '1.9.1'
gem 'omniauth-oauth2', '1.6.0'
gem 'omniauth-identity', '~> 1.1.1'
gem 'omniauth-facebook', '6.0.0'
gem 'omniauth-google-oauth2', '0.8.0'
gem 'dotenv-rails'
gem 'cloudinary', '1.13.2'
gem 'kaminari', '1.2.0'
gem 'jquery-rails', '4.3.5'
gem 'mongoid'
gem 'rexml', '~> 3.2.4'

group :development, :test do
  gem 'shoulda'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'pry-byebug'
  gem 'factory_bot_rails'
  gem 'database_cleaner-mongoid'
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-minitest'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'valid_attribute'
  gem 'faker'
end
gem 'mongoid-paperclip', require: 'mongoid_paperclip'
gem 'kaminari-mongoid', '1.0.1'
