source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.6"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.8"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Sass to process CSS
# gem "sassc-rails"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

gem 'jinda', path: '../../../jinda'
gem 'jinda_adminlte' , path: '../../../jinda_adminlte'
gem "bson", "4.4.2"
gem "maruku", "~> 0.7.3"
gem "bcrypt"
gem "rouge"
gem "normalize-rails"
gem "font-awesome-rails"
gem "font-awesome-sass", "~> 5.12.0"
gem "meta-tags"
gem "jquery-turbolinks", "2.1.0"
gem "mongo", "2.11.3"
gem "turbolinks_render"
gem "haml-rails", "~> 2.0.1"
gem "prawn"
gem "redcarpet"
gem "oauth2", "1.4.4"
gem "omniauth", "1.9.1"
gem "omniauth-oauth2", "1.6.0"
gem "omniauth-identity", "~> 1.1.1"
gem "omniauth-facebook", "6.0.0"
gem "omniauth-google-oauth2", "0.8.0"
gem "dotenv-rails"
gem "cloudinary", "1.13.2"
gem "kaminari", "1.2.0"
gem "jquery-rails", "4.3.5"
gem "mongoid"
gem "rexml", "~> 3.2.4"

group :development, :test do
  gem "shoulda"
  gem "rspec"
  gem "rspec-rails"
  gem "better_errors"
  gem "binding_of_caller"
  gem "pry-byebug"
  gem "factory_bot_rails"
  gem "database_cleaner-mongoid"
  gem "guard"
  gem "guard-rspec"
  gem "guard-minitest"
  gem "capybara"
  gem "selenium-webdriver"
  gem "rb-fsevent"
  gem "valid_attribute"
  gem "faker"
end
gem "mongoid-paperclip", require: "mongoid_paperclip"
gem "kaminari-mongoid", "1.0.1"
