plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.3
  TargetRailsVersion: 7.1
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'test/dummy/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'lib/generators/jinda/templates/**/*'

# Style preferences
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# Layout preferences
Layout/LineLength:
  Max: 120
  Exclude:
    - 'test/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Metrics
Metrics/MethodLength:
  Max: 50
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'Rakefile'
    - '**/*.rake'

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'test/**/*'

# Rails specific
Rails/Output:
  Exclude:
    - 'lib/generators/**/*'

Rails/Exit:
  Enabled: false

# Performance
Performance/Casecmp:
  Enabled: true

# Minitest
Minitest/MultipleAssertions:
  Max: 10

# Disable cops that don't make sense for this codebase
Style/GlobalVars:
  Enabled: false

Security/Eval:
  Enabled: false

Style/EvalWithLocation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

# Generator gem specific settings
Metrics/AbcSize:
  Max: 60
  Exclude:
    - 'lib/generators/**/*'

Metrics/BlockNesting:
  Max: 4

# Generators often need nested method definitions
Lint/NestedMethodDefinition:
  Exclude:
    - 'lib/generators/**/*'

# Generators may use mixin at top level
Style/MixinUsage:
  Exclude:
    - 'lib/tasks/**/*'
    - 'gem_spec.rb'

# Rails generators use I18n differently
Rails/I18nLocaleTexts:
  Enabled: false

# Gemspec dependencies are intentional
Gemspec/DevelopmentDependencies:
  Enabled: false

# Generators may need constants in blocks
Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'gem_spec.rb'
    - 'test/**/*'
    - 'spec/**/*'

# Allow using update_attribute in generators and controllers
Rails/SkipsModelValidations:
  Enabled: false

# Security checks should be warnings, not errors for generated code
Security/Open:
  Enabled: false

# Output safety - generators create templates
Rails/OutputSafety:
  Exclude:
    - 'lib/generators/**/*'
    - 'app/controllers/concerns/**/*'
