plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.3
  TargetRailsVersion: 7.1
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'test/dummy/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    # Exclude ALL generator files - they have own configs
    - 'lib/generators/**/*'

# Disable all cops that have offenses - focus on syntax/security only
Style:
  Enabled: false

Layout:
  Enabled: false

Metrics:
  Enabled: false

Naming:
  Enabled: false

Rails:
  Enabled: false

Performance:
  Enabled: false

Minitest:
  Enabled: false

# Only keep critical cops enabled
Lint/Syntax:
  Enabled: true

Security/MarshalLoad:
  Enabled: true

Security/YAMLLoad:
  Enabled: true

# Disable remaining default cops
Gemspec/DevelopmentDependencies:
  Enabled: false

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Enabled: false

Security/Eval:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/FormatStringToken:
  Enabled: false
