---

version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@3.1.2
 jobs:
   build:
     working_directory: ~/jinda/test/dummy
     docker:
       - image: cimg/ruby:2.7-node
     steps:
       - ruby/install-deps
   test:
     parallelism: 3
     docker:
       - image: cimg/ruby:2.7-node
       - image: circleci/mongo
     environment:
       BUNDLE_JOBS: "3"
       BUNDLE_RETRY: "3"
       RAILS_ENV: test
     steps:
       - checkout
       - run:
           name: Wait for DB
       - run:
           name: Database setup
           command: bundle exec rails jinda:seed
       # Run rspec in parallel
       - ruby/rspec-test
       - ruby/rubocop-check

 workflows:
   version: 2
   build_and_test:
     jobs:
       - build
       - test:
           requires:
             - build
